language: python
versions:
  - "2.7"
  - "3.5"
cache: pip
services:
  - docker

install:
  - pip install -U pip
  - pip --version
  - pip install ansible ansible-lint yamllint flake8 molecule docker
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - flake8 --version
  - molecule --version

env:
  matrix:
    - SCENARIO=answerfile_none
    - SCENARIO=answerfile_str

script:
  - molecule test -s ${SCENARIO}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
